 - hosts: jenkins
   name: install jenkins
   vars:
    jenkins_default_user_full_name: Default Jenkins User
    jenkins_default_username: default_jenkins
    jenkins_default_user_email_address: ed.epstein@invokelabs.com
    jenkins_default_user_api_token: DJtAMI3d19LbgyioNOGK777MvNP8p7BJHIIXvfgLC35oj7io7FQHl5g7AXeWpmVW
    # you cannot actually change this until the server is configured, you have to 
    # log in first and change it from the web interface.
    jenkins_default_user_password: BhPPvtmaD9
    jenkins_host_name: localhost
    jenkins_default_user_private_key: ../lib/roles/jenkins/files/private_jenkins_key_rsa
    jenkins_default_user_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDK8+MlF4m5yotTveCnmrcIj7Rko3PMhwoynlsESeXUMNQqNNM+yA6n+W3vTjO1xc+0h9QmTYtRRqgcKy7Br+TM/XoYbsqB7iqziSRcSQsIYslse8lOxQOP8ECMmtXoHdK2tfLocGNWc018P72PUyJWwUKv/DO0FjW8Gjb6qljD+nnh+XQV8eOvWSuTudVFy7Vsy4l1U4MI1yF42VZsHxYHE7tPUh0suEIMHNBqPDwHIyF+vEPgMmFsyUkD4OFxxzDRDGcXa1X/Dx/CW3EjixIFoz61pWVQlbGt8+AtW2l/XpUegj558z3GmIflRbDNwyExrkMXkUe9z06YbwGe9bptmzhw8cmzgT0xCUHmpMvaqF43/Io3bCyfNoHFdr+WTyWZ58NCt70OoLcKMGQG+M0ZxM7S5TTfrgYsmbspMCbVkUz4dsEZ3XXZTg4y2ktXx3ZInVEPNamwPXWk+7ZCszBnlShVuULXbKOh8zbboZM8M3uIUa7F3gfqxPqk+7b67BHMStPizUjNzvdwHVWKmhZ6Xn01Xk12utvaFtDXZwfj1f5Cm068bb990RYKQ4xIVYHePt0tzOyQ3uLdWLUmGKTDdvfL2sVy95Qsm2tgks3TftUkI2UwXKomOb2i3aUjytNG+oMz1OlBXD/6tgHPgUsJhrjCVmsj6oxN5we6oZgMhQ==
    # if you change the below to False, then you need to provide local paths
    # to the certificate and certificate's private key.
    jenkins_use_self_signed_certificate: True
    #jenkins_certificate_path:
    #jenkins_certificate_key_path:
    # If you change the below to True, then you need to provide the relay
    # hostnmae, SMTP AUTH username, and SMTP AUTH password.
    jenkins_use_mail_relay_host: False 
    jenkins_mail_relay_host: smtp.mandrillapp.com
    jenkins_mail_relay_smtp_username: sysadmin@invokelabs.com
    jenkins_mail_relay_host_smtp_password: wG748vvrNJZL5uAY8ASGjA
   roles:
    - ../../lib/roles/jenkins